### ISSUE TITLE
Figura's emojis causes custom mob names to appear empty

### ISSUE THREAD

**Issue by mintynoura** [Estecka/mc-ALL-Death-Messages#6] opened 2023-12-15 20:23 UTC
I don't know why, but named mobs get empty names in chat messages. Tested in creative with default config and gamerules

**Versions:**
Minecraft 1.20.1
All Death Messages 1.5.4
Quilt loader 0.21.0
QFAPI 7.4.0 and QSL 6.1.2

![image](https://github.com/Estecka/mc-ALL-Death-Messages/assets/107040228/b1a95a2a-6c69-40f4-80a5-06993c88e56e)

**Comment by Estecka** [comment] 2023-12-15 20:51
I'll have a look at this later, but until then, here's a small test that will help narrow the issue: Can you check what happens if you remove the `underline` property of named mobs, in the "styles" config file ?

**Comment by mintynoura** [comment] 2023-12-15 21:02
The issue persists after removing it

**Comment by Estecka** [comment] 2023-12-16 02:13
I wasn't able to reproduce this with just the specified versions. I'll need more information; a log would be immensely useful.

Did you have any other mod installed ? Try using the command `/alldeathmsg test` on the bugged mob; is its name also empty in the command's result ? Was there anything particular about the mob, the death, the name, or the tag ?

Another thing that bugs me is the colour of your name in the screenshot; it looks different from that of the default config. Did you customize the styles ?

**Comment by mintynoura** [comment] 2023-12-16 07:22
Hm, it might be an incompatibility in my modpack. It has ~200 mods so it’s
gonna take a while for me to figure out what’s causing it.

Nothing was special about the mob or the nametag, and the logs don’t seem
to mention anything about it.

My name colour was different because of a datapack from Vanilla Tweaks that
lets you change that colour, but i did try disabling it in that modpack and
the issue still appeared so i doubt it was caused by that

**Comment by mintynoura** [comment] 2023-12-16 11:05
I did some testing with the command. The name is also empty in the test command output

![image](https://github.com/Estecka/mc-ALL-Death-Messages/assets/107040228/ef2e4a3f-1ab8-4fff-abba-e22e1b8a546e)

i looked at the server log and the death message looks like it knows the name:
`[13:57:52] [Server thread/INFO]:  was slain by mintynoura`
`[13:57:52] [Server thread/INFO]: Death message triggered by Test_name (entity.minecraft.chicken) using rule showDeathMessages.named.death`
`[13:57:52] [Render thread/INFO]: [System] [CHAT]  was slain by mintynoura`

i'll do binary testing to figure out what mod is conflicting

**Comment by Estecka** [comment] 2023-12-16 13:46
That one log message obtains the name from a different method (`getName` instead of `getDisplayName`), and doesn't attempt to add any styles to the name, so this suggests a mod that changes the way custom names are formatted, one way or another.
The name is still missing from the first server log, so it is a server-side mod or a datapack.

In your binary testing, you should also try disabling All-Death-Messages, and trigger a message by killing a tamed pet. If its name still doesn't appear, then its not an incompatibility that involves my mod.
Are the nameplates above mob heads still visible ? Are there any other places in the game where the mob's name _can_ be seen ?

**Comment by mintynoura** [comment] 2023-12-16 16:41
I found the culprit, it was Figura.

Nameplates are still visible with All Death Messages, and without it, the tamed pet death message showed their name. So i guess something with Figura is messing with entity names that makes their death messages blank with All Death Messages

**Comment by Estecka** [comment] 2023-12-16 18:45
I was able to reproduce it.

This seems to be related to their emoji feature, although I don't yet know why it only affects named mobs.
For now you can disable this feature in their settings, under 'misc', but this will only fix new named mobs. I don't know what Figura is doing to them, but existing mobs remain broken even after uninstalling Figura.

**Comment by mintynoura** [comment] 2023-12-16 18:50
Aw well. Thank you for your help still :)
All Death Messages a wonderful mod

**Comment by Estecka** [comment] 2023-12-16 22:23
So the reason only named mobs were affected is because they inherited their name from an item (either a spawn egg or a nametag). Figura [aggresively processes item names](https://github.com/FiguraMC/Figura/blob/1.20/common/src/main/java/org/figuramc/figura/mixin/ItemStackMixin.java) everywhere they are used; in singleplayer, it ends up reformatting mob names on the server-side of the game. Presumably, mobs spawned through commands or in multiplayer would be unaffected.

I definitely think there's some bug being cooked up on their side, but it is not the core of this issue. This did highlight some shortcomings on how _I_ was styling mob names, so I'll be able to come up with a fix from my side.

**Comment by Estecka** [comment] 2023-12-17 02:19
Fixed in 1.5.5

**Closed as completed by Estecka** 2023-12-17 02:19 UTC
Labels: bug, compatibility
